# Generated by Django 2.1.1 on 2019-02-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_content', models.CharField(blank=True, max_length=512, null=True, verbose_name='审计内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '审计日志表',
                'db_table': 'auditlog',
            },
        ),
        migrations.CreateModel(
            name='MyAuthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(max_length=32, verbose_name='认证类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '认证类型',
                'db_table': 'myauthtype',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('describe', models.CharField(blank=True, max_length=512, null=True, verbose_name='项目描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '项目表',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(blank=True, max_length=32, null=True, verbose_name='登陆用户')),
                ('key', models.TextField(blank=True, null=True, verbose_name='密钥字符串')),
                ('key_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密钥解密密码/用户密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('auth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_models.MyAuthType', verbose_name='认证类型')),
            ],
            options={
                'verbose_name_plural': '密码表',
                'db_table': 'secretkey',
            },
        ),
        migrations.CreateModel(
            name='ServerHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名字')),
                ('host_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='ip地址')),
                ('host_port', models.IntegerField(verbose_name='ssh端口')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databases_models.Project', verbose_name='属于哪个项目')),
            ],
            options={
                'verbose_name_plural': '机器表',
                'db_table': 'serverhost',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务名称')),
                ('op_task', models.CharField(blank=True, max_length=512, null=True, verbose_name='执行内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(choices=[(0, '未执行'), (1, '已执行'), (2, '执行中'), (3, '不执行')], default=3, verbose_name='执行状态')),
                ('done_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name_plural': '任务表',
                'db_table': 'tasklist',
            },
        ),
        migrations.CreateModel(
            name='TaskRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_content', models.TextField(verbose_name='执行结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databases_models.TaskList', verbose_name='属于哪个任务')),
            ],
            options={
                'verbose_name_plural': '执行结果表',
                'db_table': 'taskres',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系号码')),
                ('phone_bak', models.CharField(blank=True, max_length=64, null=True, verbose_name='备用联系号码')),
                ('motto', models.CharField(blank=True, max_length=512, null=True, verbose_name='座右铭')),
                ('hobby', models.CharField(blank=True, max_length=512, null=True, verbose_name='兴趣爱好')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ManyToManyField(to='databases_models.Project', verbose_name='用户负责的项目')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '用户类型表',
                'db_table': 'usertype',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_models.UserType', verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databases_models.User', verbose_name='属于哪个用户'),
        ),
        migrations.AddField(
            model_name='serverhost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_models.User', verbose_name='属于哪个用户'),
        ),
        migrations.AddField(
            model_name='secretkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_models.User', verbose_name='属于哪个用户'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='op_host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databases_models.ServerHost', verbose_name='操作关联机器'),
        ),
    ]
