# Generated by Django 2.1.1 on 2019-02-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases_models', '0002_auto_20190219_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_models.Project', verbose_name='属于哪个项目'),
        ),
    ]
