# Generated by Django 2.1.1 on 2019-03-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases_models', '0004_devrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverhost',
            old_name='project',
            new_name='b_project',
        ),
    ]
