# Generated by Django 2.1.1 on 2019-03-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='ip地址')),
                ('cpu_percent', models.CharField(blank=True, max_length=64, null=True, verbose_name='cpu使用率')),
                ('cpu_user_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='cpu用户时间')),
                ('cpu_system_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='cpu系统时间')),
                ('cpu_iowait_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='iowait_time')),
                ('memory_total', models.CharField(blank=True, max_length=64, null=True, verbose_name='总内存')),
                ('memory_percent', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存使用率')),
                ('memory_available', models.CharField(blank=True, max_length=64, null=True, verbose_name='可用内存')),
            ],
            options={
                'db_table': 'monitor_info',
                'verbose_name_plural': '监控信息表',
            },
        ),
    ]
