# Generated by Django 2.1.1 on 2019-03-06 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
